name: Deploy to Codespace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-flask-app:latest

      - name: Deploy to Codespace via GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh codespace ssh -c "${{ secrets.CODESPACE_NAME }}" -- "
            set -e
            
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-flask-app:latest
            
            docker rm -f flask-container || true
            
            docker run -d --name flask-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/simple-flask-app:latest
          "